#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "e5QbK/3vo60A"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

#define CIRQUE_PINNALE_TAP_ENABLE
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 3
